import { FISH, MEDICINES, RODS, TICKET_ID } from "../../items";
import { PETS } from "../../pets";
import type { CityInfo } from "../types";

/**
 * Ciudad Vieja: nombre, descripción, edificios emblemáticos y tiendas. Es lo liviano del barrio: el
 * cliente lo tiene siempre (lista de barrios, landing, tiendas); el mapa (`map.ts`) se descarga al entrar.
 */

export const CIUDAD_VIEJA_INFO = {
  id: "ciudad-vieja",
  name: "Ciudad Vieja",
  description: "El casco histórico de Montevideo, entre el puerto y la Plaza Independencia.",
  landmarks: [
    {
      id: "puerta-ciudadela",
      name: "Puerta de la Ciudadela",
      description: "Único resto de la muralla colonial; separa la Ciudad Vieja de la Plaza Independencia.",
      kind: "gate",
      area: { x: 53, y: 22, width: 1, height: 5 },
      passable: [{ x: 53, y: 24 }],
    },
    {
      id: "monumento-artigas",
      name: "Monumento a Artigas",
      description: "Estatua ecuestre de José Artigas en el centro de la Plaza Independencia.",
      kind: "equestrianMonument",
      area: { x: 62, y: 24, width: 3, height: 3 },
    },
    {
      id: "palacio-salvo",
      name: "Palacio Salvo",
      description: "El rascacielos de 1928 que domina la Plaza Independencia.",
      kind: "palacioSalvo",
      area: { x: 67, y: 7, width: 5, height: 5 },
    },
    {
      id: "teatro-solis",
      name: "Teatro Solís",
      description: "El teatro más antiguo del país (1856), con su pórtico de columnas.",
      kind: "theater",
      area: { x: 46, y: 33, width: 5, height: 5 },
    },
    {
      id: "catedral",
      name: "Catedral Metropolitana",
      description: "La Iglesia Matriz, frente a la Plaza Matriz, con sus dos torres.",
      kind: "cathedral",
      area: { x: 21, y: 18, width: 4, height: 4 },
    },
    {
      id: "cabildo",
      name: "Cabildo de Montevideo",
      description: "Sede del gobierno colonial; hoy museo histórico.",
      kind: "cabildo",
      area: { x: 29, y: 11, width: 4, height: 4 },
    },
    {
      id: "fuente-plaza-matriz",
      name: "Fuente de la Plaza Matriz",
      description: "La fuente de 1871 en el centro de la plaza más antigua de la ciudad.",
      kind: "fountain",
      area: { x: 30, y: 19, width: 2, height: 2 },
    },
    {
      id: "escollera-sarandi",
      name: "Escollera Sarandí",
      description: "Espigón sobre el Río de la Plata con su farola. Parado en la escollera se puede pescar.",
      kind: "lighthouse",
      area: { x: 16, y: 56, width: 1, height: 1 },
    },
    {
      id: "escollera-sarandi-este",
      name: "Escollera Sarandí (este)",
      description: "Segundo espigón, frente a la Plaza Independencia, con su farola. También se pesca.",
      kind: "lighthouse",
      area: { x: 63, y: 56, width: 1, height: 1 },
    },
    {
      id: "mercado-puerto",
      name: "Mercado del Puerto",
      description: "Estructura de hierro de 1868 junto al puerto, famosa por sus parrillas.",
      kind: "market",
      area: { x: 8, y: 3, width: 5, height: 5 },
    },
  ],
  shops: [
    {
      id: "agencia-stm",
      name: "Agencia STM",
      description: "Sobre la Rambla 25 de Agosto: vende boletos de ómnibus para viajar entre barrios.",
      area: { x: 27, y: 3, width: 2, height: 2 },
      building: "stm",
      stock: [TICKET_ID],
      buys: ["ticket"],
    },
    {
      id: "roperia-sarandi",
      name: "Ropería Sarandí",
      description: "Tienda de ropa de la peatonal: compra y vende prendas.",
      area: { x: 39, y: 21, width: 2, height: 2 },
      building: "clothing",
      buys: ["clothing"],
      stock: [
        "remera-blanca",
        "remera-roja",
        "remera-negra",
        "camiseta-celeste",
        "buzo-gris",
        "musculosa-blanca",
        "jean",
        "pantalon-beige",
        "short-verde",
        "short-azul",
        "championes-blancos",
        "championes-rojos",
        "botas-marrones",
        "chancletas",
        "gorra-azul",
        "gorro-lana",
        "boina-negra",
      ],
    },
    {
      id: "kiosco-independencia",
      name: "Kiosco de la Plaza",
      description: "En la Plaza Independencia: tortas fritas, alfajores y mate para seguir laburando.",
      area: { x: 54, y: 18, width: 2, height: 2 },
      building: "kiosk",
      stock: ["torta-frita", "alfajor", "mate"],
      buys: [],
    },
    {
      id: "farmacia-sarandi",
      name: "Farmacia Sarandí",
      description: "Sobre la peatonal, al lado de la veterinaria: Perifar, curitas, vitaminas y botiquines para la salud.",
      area: { x: 48, y: 22, width: 2, height: 2 },
      building: "pharmacy",
      stock: MEDICINES.map((item) => item.id),
      buys: [],
    },
    {
      id: "veterinaria-sarandi",
      name: "Veterinaria Sarandí",
      description: "Sobre la peatonal: adoptá una mascota, ponele nombre y te acompaña a todos lados.",
      area: { x: 46, y: 22, width: 2, height: 2 },
      building: "pets",
      stock: [],
      buys: [],
      pets: PETS.map((pet) => pet.id),
    },
    {
      id: "pescaderia-mercado",
      name: "Pescadería del Mercado",
      description:
        "En el Mercado del Puerto te compran lo que pescaste a precio completo y venden todos los pescados del río (más caros). En las parrillas, chivito y pescado a la plancha.",
      area: { x: 8, y: 3, width: 5, height: 5 },
      building: "none",
      stock: ["chivito", "pescado-plancha", ...FISH.map((fish) => fish.id)],
      buys: ["fish"],
    },
    {
      id: "tienda-pesca",
      name: "Pesca Sarandí",
      description: "Frente a la Escollera Sarandí: vende cañas (las mejores pescan mejor) y compra las usadas.",
      area: { x: 9, y: 40, width: 2, height: 2 },
      building: "fishing",
      stock: RODS.map((rod) => rod.id),
      buys: ["rod"],
    },
  ],
} satisfies CityInfo;
